[package]
name = "smtc-modem-cores-sys"
version = "0.1.0"
authors = ["Louis Thiery <thiery.louis@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
bindgen = {version="=0", default-features = false }
cc = "1"
cmake = "0"

[dependencies]
cty =  "0.2"
libm = "0"
