//! Zero-copy parsing of LoRaWAN frames as borrowed views.
//!
//! This module replaced the earlier `T: AsRef<[u8]>` generic-over-storage
//! design:
//!
//! * Fixed-size wire fields ([`DevAddr`], [`DevEui`], [`JoinEui`],
//!   [`DevNonce`], [`JoinNonce`], [`NetId`], [`Frequency`]) become plain
//!   owned `[u8; N]` newtypes (`Copy`, `Eq`, `Hash`) with explicit
//!   wire-order/value conversions.
//! * Parsing produces zero-copy read-only views with all structural
//!   validation done once at the boundary, so every accessor afterwards is
//!   infallible by construction. One monomorphization regardless of where the
//!   bytes live.
//! * Decryption stays in place but takes the `&mut [u8]` explicitly, keeping
//!   the encrypted/decrypted typestate without any storage generic.
//! * MAC command parsing ([`crate::maccommands`], [`crate::certification`],
//!   [`crate::multicast`]) yields `Result` per command instead of silently
//!   stopping at malformed input,
//!   with the framing generated by the `CommandHandler` derive from the
//!   enums' `#[cmd]` attributes.
//! * Frames are built from plain structs ([`DataFrame`], [`JoinRequest`],
//!   [`JoinAccept`]) with `build_into(&mut buf)`; the types make most
//!   invalid frames unrepresentable.
//! * One [`Error`] enum implementing `Display` and `core::error::Error`.
//!
//! Deliberate divergences from the retired design, for anyone migrating:
//!
//! * `f_port()` returns `Some` when an FPort byte is present with an empty
//!   FRMPayload. The old code reported `None` in that case, conflating
//!   "FPort absent" with "FPort present, payload empty".
//! * Wire fields are explicit about byte order: the wire transmits them
//!   little-endian, so `from_value`/`value` convert accordingly. The old
//!   `From<u32> for DevAddr` and `From<u16> for DevNonce` used big-endian
//!   array order, which round-tripped through the wire with flipped
//!   endianness.
//! * All parse entry points reject frames with a non-R1 major version; the
//!   old `EncryptedDataPayload::new` accepted them.
//! * A MAC command stream with a malformed tail yields `Err`; the old
//!   iterator ended silently.
//!
//! # Examples
//!
//! Receiving on a device: inspect the frame read-only, look up the session
//! by [`DevAddr`], verify the MIC, then decrypt in place.
//!
//! ```
//! use lorawan::default_crypto::DefaultCrypto;
//! use lorawan::keys::{AppSKey, NwkSKey};
//! use lorawan::parser::{DecryptedDataPayload, DevAddr, EncryptedDataPayload, FrmPayload};
//!
//! let mut buf = [
//!     0x40, 0x04, 0x03, 0x02, 0x01, 0x80, 0x01, 0x00, 0x01, 0xa6, 0x94, 0x64, 0x26, 0x15,
//!     0xd6, 0xc3, 0xb5, 0x82,
//! ];
//! let nwk_crypto = DefaultCrypto::new(NwkSKey::from([2; 16]).inner());
//! let app_crypto = DefaultCrypto::new(AppSKey::from([1; 16]).inner());
//!
//! let phy = EncryptedDataPayload::parse(&buf).unwrap();
//! assert_eq!(phy.fhdr().dev_addr(), DevAddr::from_value(0x01020304));
//! assert!(phy.validate_mic(&nwk_crypto, 1));
//!
//! let decrypted =
//!     DecryptedDataPayload::decrypt_in_place(&mut buf, Some(&nwk_crypto), Some(&app_crypto), 1)
//!         .unwrap();
//! assert_eq!(decrypted.frm_payload(), FrmPayload::Data(b"hello"));
//! ```
//!
//! Sending: describe the frame with a struct literal and build it into a
//! caller-provided buffer.
//!
//! ```
//! use core::num::NonZeroU8;
//! use lorawan::default_crypto::DefaultCrypto;
//! use lorawan::keys::{AppSKey, NwkSKey};
//! use lorawan::creator::{DataFrame, Payload};
//! use lorawan::parser::{DataFrameType, DevAddr};
//!
//! let frame = DataFrame {
//!     frame_type: DataFrameType::ConfirmedUp,
//!     dev_addr: DevAddr::from_value(0x01020304),
//!     adr: true,
//!     fcnt: 42,
//!     payload: Payload::Data { f_port: NonZeroU8::new(1).unwrap(), data: b"hello" },
//!     ..Default::default()
//! };
//! let mut buf = [0u8; 64];
//! let nwk_crypto = DefaultCrypto::new(NwkSKey::from([2; 16]).inner());
//! let app_crypto = DefaultCrypto::new(AppSKey::from([1; 16]).inner());
//! let bytes = frame.build_into(&mut buf, &nwk_crypto, Some(&app_crypto)).unwrap();
//! assert_eq!(bytes.len(), 18);
//! ```

use crate::keys::{AppSKey, Crypto, NwkSKey, AES128, MIC};
use crate::packet_length::phy::join::{
    JOIN_ACCEPT_LEN, JOIN_ACCEPT_WITH_CFLIST_LEN, JOIN_REQUEST_LEN,
};
use crate::packet_length::phy::{MHDR_LEN, MIC_LEN};
use crate::securityhelpers;
use crate::types::{ChannelMask, DLSettings};

/// Errors from parsing or decrypting a LoRaWAN frame.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt-03", derive(defmt::Format))]
pub enum Error {
    /// The buffer is shorter than the smallest possible frame.
    TooShort,
    /// The MHDR major version is not LoRaWAN R1.
    UnsupportedMajorVersion,
    /// The MHDR message type is RFU or Proprietary.
    UnsupportedMessageType,
    /// The MHDR message type does not match the frame type being parsed.
    UnexpectedMessageType,
    /// The MHDR message type is not one of the four data frame types.
    NotADataFrame,
    /// The buffer length is not valid for this frame type.
    InvalidLength,
    /// FOptsLen claims more FOpts bytes than the frame contains.
    TruncatedFhdr,
    /// No key was supplied for the FPort carried by this frame.
    MissingKey,
    /// The MIC does not match the frame contents.
    InvalidMic,
    /// The output buffer is too small for the frame being built.
    BufferTooShort,
    /// FOpts is limited to 15 bytes.
    FOptsTooLong,
    /// The spec forbids FPort 0 (MAC commands in FRMPayload) together with a
    /// non-empty FOpts.
    FOptsWithFPortZero,
}

impl core::fmt::Display for Error {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let s = match self {
            Error::BufferTooShort => "output buffer too small for the frame",
            Error::FOptsTooLong => "FOpts is limited to 15 bytes",
            Error::FOptsWithFPortZero => "FPort 0 with non-empty FOpts is forbidden",
            Error::TooShort => "buffer shorter than minimal frame",
            Error::UnsupportedMajorVersion => "unsupported LoRaWAN major version",
            Error::UnsupportedMessageType => "RFU or proprietary MHDR message type",
            Error::UnexpectedMessageType => "MHDR message type does not match frame type",
            Error::NotADataFrame => "MHDR message type is not a data frame",
            Error::InvalidLength => "buffer length invalid for this frame type",
            Error::TruncatedFhdr => "FOptsLen exceeds frame length",
            Error::MissingKey => "no key supplied for this frame's FPort",
            Error::InvalidMic => "MIC mismatch",
        };
        f.write_str(s)
    }
}

impl core::error::Error for Error {}

/// A parsed LoRaWAN physical payload: a read-only view classified by MHDR.
#[derive(Debug, Clone, Copy)]
pub enum PhyPayload<'a> {
    JoinRequest(JoinRequestPayload<'a>),
    JoinAccept(EncryptedJoinAcceptPayload<'a>),
    Data(EncryptedDataPayload<'a>),
}

/// Parses and classifies a LoRaWAN physical payload.
#[inline]
pub fn parse(bytes: &[u8]) -> Result<PhyPayload<'_>, Error> {
    let [mhdr, ..] = bytes else {
        return Err(Error::TooShort);
    };
    if mhdr & 0b11 != 0 {
        return Err(Error::UnsupportedMajorVersion);
    }
    match mhdr >> 5 {
        0 => Ok(PhyPayload::JoinRequest(JoinRequestPayload::parse(bytes)?)),
        1 => Ok(PhyPayload::JoinAccept(EncryptedJoinAcceptPayload::parse(bytes)?)),
        2..=5 => Ok(PhyPayload::Data(EncryptedDataPayload::parse(bytes)?)),
        _ => Err(Error::UnsupportedMessageType),
    }
}

// --- Data frames ---------------------------------------------------------

/// The four data frame message types.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt-03", derive(defmt::Format))]
pub enum DataFrameType {
    UnconfirmedUp,
    UnconfirmedDown,
    ConfirmedUp,
    ConfirmedDown,
}

impl DataFrameType {
    #[inline]
    fn from_mhdr(mhdr: u8) -> Option<Self> {
        match mhdr >> 5 {
            2 => Some(Self::UnconfirmedUp),
            3 => Some(Self::UnconfirmedDown),
            4 => Some(Self::ConfirmedUp),
            5 => Some(Self::ConfirmedDown),
            _ => None,
        }
    }

    #[inline]
    pub fn is_uplink(self) -> bool {
        matches!(self, Self::UnconfirmedUp | Self::ConfirmedUp)
    }

    #[inline]
    pub fn is_confirmed(self) -> bool {
        matches!(self, Self::ConfirmedUp | Self::ConfirmedDown)
    }
}

/// Zero-copy view of the FHDR of a data frame.
///
/// Only constructed by [`EncryptedDataPayload::parse`] /
/// [`DecryptedDataPayload`], which validate the length invariant
/// (`bytes.len() == 7 + f_opts_len`), so accessors cannot panic.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Fhdr<'a> {
    bytes: &'a [u8],
    uplink: bool,
}

impl<'a> Fhdr<'a> {
    #[inline]
    pub fn dev_addr(&self) -> DevAddr {
        DevAddr::from_wire_bytes(arr(&self.bytes[0..4]))
    }

    /// The address field interpreted as a multicast group address, for frames
    /// received in a multicast session.
    #[inline]
    pub fn mc_addr(&self) -> McAddr {
        McAddr::from_wire_bytes(arr(&self.bytes[0..4]))
    }

    #[inline]
    pub fn fctrl(&self) -> FCtrl {
        FCtrl::new(self.bytes[4], self.uplink)
    }

    /// The truncated 16-bit frame counter from the wire.
    #[inline]
    pub fn fcnt(&self) -> u16 {
        u16::from_le_bytes([self.bytes[5], self.bytes[6]])
    }

    /// The FOpts bytes (may be empty). Length was validated at parse time.
    #[inline]
    pub fn f_opts(&self) -> &'a [u8] {
        &self.bytes[7..]
    }
}

/// Layout facts computed once during validation and shared by both payload
/// views. Offsets are guaranteed in bounds for the buffer they were computed
/// from.
#[derive(Debug, Clone, Copy)]
struct Layout {
    frame_type: DataFrameType,
    fhdr_len: usize,
    /// Offset of the FPort byte, if present.
    f_port_offset: Option<usize>,
    /// FRMPayload byte range (empty if absent).
    frm_start: usize,
    frm_end: usize,
}

impl Layout {
    /// Validates the structure of a data frame. This is the single place
    /// bounds are checked; every view accessor relies on it.
    #[inline]
    fn validate(bytes: &[u8]) -> Result<Self, Error> {
        // MHDR (1) + DevAddr (4) + FCtrl (1) + FCnt (2) + MIC (4)
        const MIN_LEN: usize = MHDR_LEN + 7 + MIC_LEN;
        if bytes.len() < MIN_LEN {
            return Err(Error::TooShort);
        }
        let mhdr = bytes[0];
        if mhdr & 0b11 != 0 {
            return Err(Error::UnsupportedMajorVersion);
        }
        let frame_type = DataFrameType::from_mhdr(mhdr).ok_or(Error::NotADataFrame)?;
        let fhdr_len = 7 + (bytes[5] & 0x0f) as usize;
        let mic_offset = bytes.len() - MIC_LEN;
        // FHDR must fit between MHDR and MIC.
        if MHDR_LEN + fhdr_len > mic_offset {
            return Err(Error::TruncatedFhdr);
        }
        let after_fhdr = MHDR_LEN + fhdr_len;
        let (f_port_offset, frm_start) = if after_fhdr < mic_offset {
            (Some(after_fhdr), after_fhdr + 1)
        } else {
            (None, after_fhdr)
        };
        Ok(Self { frame_type, fhdr_len, f_port_offset, frm_start, frm_end: mic_offset })
    }
}

macro_rules! data_view_accessors {
    () => {
        #[inline]
        pub fn frame_type(&self) -> DataFrameType {
            self.layout.frame_type
        }

        #[inline]
        pub fn is_uplink(&self) -> bool {
            self.layout.frame_type.is_uplink()
        }

        #[inline]
        pub fn is_confirmed(&self) -> bool {
            self.layout.frame_type.is_confirmed()
        }

        #[inline]
        pub fn fhdr(&self) -> Fhdr<'a> {
            Fhdr {
                bytes: &self.bytes[MHDR_LEN..MHDR_LEN + self.layout.fhdr_len],
                uplink: self.is_uplink(),
            }
        }

        /// The FPort, if the frame carries one.
        ///
        /// A present FPort with an empty FRMPayload is reported as `Some`
        /// (the retired parser conflated it with no-FPort).
        #[inline]
        pub fn f_port(&self) -> Option<u8> {
            self.layout.f_port_offset.map(|off| self.bytes[off])
        }

        #[inline]
        pub fn mic(&self) -> MIC {
            let mic = &self.bytes[self.bytes.len() - MIC_LEN..];
            MIC([mic[0], mic[1], mic[2], mic[3]])
        }

        /// The raw frame bytes.
        #[inline]
        pub fn as_bytes(&self) -> &'a [u8] {
            self.bytes
        }
    };
}

/// Zero-copy read-only view of an encrypted data frame.
///
/// One monomorphization regardless of where the bytes live; inspect the
/// header, look up session keys by [`DevAddr`], check the MIC, then hand the
/// mutable buffer to [`DecryptedDataPayload::decrypt_in_place`].
#[derive(Debug, Clone, Copy)]
pub struct EncryptedDataPayload<'a> {
    bytes: &'a [u8],
    layout: Layout,
}

impl<'a> EncryptedDataPayload<'a> {
    /// Parses and structurally validates an encrypted data frame.
    #[inline]
    pub fn parse(bytes: &'a [u8]) -> Result<Self, Error> {
        let layout = Layout::validate(bytes)?;
        Ok(Self { bytes, layout })
    }

    data_view_accessors!();

    /// Whether the MIC matches under the given 32-bit frame counter.
    ///
    /// `crypto` must be bound to the NwkSKey (or McNetSKey for multicast).
    #[inline]
    pub fn validate_mic<C: Crypto>(&self, crypto: &C, fcnt: u32) -> bool {
        let without_mic = &self.bytes[..self.bytes.len() - MIC_LEN];
        self.mic() == securityhelpers::calculate_data_mic(without_mic, crypto, fcnt)
    }
}

/// A decrypted data frame, borrowing the buffer that was decrypted in place.
///
/// Only obtainable through [`Self::decrypt_in_place`] or
/// [`Self::check_mic_and_decrypt_in_place`], which preserves the
/// encrypted/decrypted typestate of the old design without a storage generic.
#[derive(Debug)]
pub struct DecryptedDataPayload<'a> {
    bytes: &'a [u8],
    layout: Layout,
}

/// The decrypted FRMPayload contents.
#[derive(Debug, PartialEq, Eq)]
pub enum FrmPayload<'a> {
    /// Application data (FPort > 0).
    Data(&'a [u8]),
    /// MAC commands (FPort == 0).
    MacCommands(&'a [u8]),
    /// The frame carries no FRMPayload.
    None,
}

impl<'a> DecryptedDataPayload<'a> {
    /// Parses `buf` and decrypts its FRMPayload in place.
    ///
    /// Does NOT verify the MIC; prefer [`Self::check_mic_and_decrypt_in_place`]
    /// unless the MIC was already checked via
    /// [`EncryptedDataPayload::validate_mic`].
    ///
    /// Key selection follows the spec: `app_crypto` (bound to the AppSKey, or
    /// McAppSKey for multicast) decrypts FPort > 0, `nwk_crypto` (bound to
    /// the NwkSKey or McNetSKey) decrypts FPort 0 (MAC commands). Only the
    /// crypto the frame actually needs must be present. `fcnt` supplies the
    /// upper 16 bits of the frame counter; the lower 16 come from the wire.
    #[inline]
    pub fn decrypt_in_place<C: Crypto>(
        buf: &'a mut [u8],
        nwk_crypto: Option<&C>,
        app_crypto: Option<&C>,
        fcnt: u32,
    ) -> Result<Self, Error> {
        let layout = Layout::validate(buf)?;
        if layout.frm_start < layout.frm_end {
            let uses_app_key = matches!(layout.f_port_offset, Some(off) if buf[off] != 0);
            let crypto = if uses_app_key {
                app_crypto
            } else {
                nwk_crypto
            };
            let crypto = crypto.ok_or(Error::MissingKey)?;
            let wire_fcnt = u16::from_le_bytes([buf[6], buf[7]]);
            let full_fcnt = ((fcnt >> 16) << 16) | u32::from(wire_fcnt);
            securityhelpers::encrypt_frm_data_payload(
                buf,
                layout.frm_start,
                layout.frm_end,
                full_fcnt,
                crypto,
            );
        }
        Ok(Self { bytes: buf, layout })
    }

    /// Verifies the MIC with `nwk_skey`, then decrypts in place.
    ///
    /// The MIC is checked before anything is written, so on `InvalidMic` the
    /// buffer still holds the received bytes unchanged.
    #[inline]
    pub fn check_mic_and_decrypt_in_place<C: Crypto>(
        buf: &'a mut [u8],
        nwk_crypto: &C,
        app_crypto: Option<&C>,
        fcnt: u32,
    ) -> Result<Self, Error> {
        if !EncryptedDataPayload::parse(buf)?.validate_mic(nwk_crypto, fcnt) {
            return Err(Error::InvalidMic);
        }
        Self::decrypt_in_place(buf, Some(nwk_crypto), app_crypto, fcnt)
    }

    data_view_accessors!();

    /// The decrypted FRMPayload.
    #[inline]
    pub fn frm_payload(&self) -> FrmPayload<'a> {
        let frm = &self.bytes[self.layout.frm_start..self.layout.frm_end];
        match self.f_port() {
            None => FrmPayload::None,
            Some(0) => FrmPayload::MacCommands(frm),
            Some(_) => FrmPayload::Data(frm),
        }
    }
}

// --- JoinRequest / JoinAccept --------------------------------------------

#[inline]
fn check_mhdr(bytes: &[u8], mtype: u8) -> Result<(), Error> {
    let [mhdr, ..] = bytes else {
        return Err(Error::TooShort);
    };
    if mhdr & 0b11 != 0 {
        return Err(Error::UnsupportedMajorVersion);
    }
    if mhdr >> 5 != mtype {
        return Err(Error::UnexpectedMessageType);
    }
    Ok(())
}

#[inline]
fn extract_mic(bytes: &[u8]) -> MIC {
    MIC(arr(&bytes[bytes.len() - MIC_LEN..]))
}

/// Zero-copy view of a JoinRequest frame.
///
/// The fixed 23-byte length is checked once at parse time; the fixed-size
/// reference makes every accessor's bounds visible to the compiler.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct JoinRequestPayload<'a> {
    bytes: &'a [u8; JOIN_REQUEST_LEN],
}

impl<'a> JoinRequestPayload<'a> {
    /// Parses and structurally validates a JoinRequest.
    #[inline]
    pub fn parse(bytes: &'a [u8]) -> Result<Self, Error> {
        check_mhdr(bytes, 0)?;
        let bytes = bytes.try_into().map_err(|_| Error::InvalidLength)?;
        Ok(Self { bytes })
    }

    /// The JoinEUI (called AppEUI before LoRaWAN 1.0.4).
    #[inline]
    pub fn join_eui(&self) -> JoinEui {
        JoinEui::from_wire_bytes(arr(&self.bytes[1..9]))
    }

    #[inline]
    pub fn dev_eui(&self) -> DevEui {
        DevEui::from_wire_bytes(arr(&self.bytes[9..17]))
    }

    #[inline]
    pub fn dev_nonce(&self) -> DevNonce {
        DevNonce::from_wire_bytes(arr(&self.bytes[17..19]))
    }

    #[inline]
    pub fn mic(&self) -> MIC {
        extract_mic(self.bytes)
    }

    /// Whether the MIC matches under the device's root key.
    ///
    /// `crypto` must be bound to the AppKey.
    #[inline]
    pub fn validate_mic<C: Crypto>(&self, crypto: &C) -> bool {
        let without_mic = &self.bytes[..JOIN_REQUEST_LEN - MIC_LEN];
        self.mic() == securityhelpers::calculate_mic(without_mic, crypto)
    }

    /// The raw frame bytes.
    #[inline]
    pub fn as_bytes(&self) -> &'a [u8] {
        self.bytes
    }
}

#[inline]
fn validate_join_accept_structure(bytes: &[u8]) -> Result<(), Error> {
    check_mhdr(bytes, 1)?;
    if bytes.len() != JOIN_ACCEPT_LEN && bytes.len() != JOIN_ACCEPT_WITH_CFLIST_LEN {
        return Err(Error::InvalidLength);
    }
    Ok(())
}

/// Zero-copy view of a still-encrypted JoinAccept frame.
///
/// Nothing but the MHDR is readable before decryption; the payload (including
/// its MIC) is encrypted with the AppKey. Hand the mutable buffer to
/// [`DecryptedJoinAcceptPayload::decrypt_in_place`] to proceed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EncryptedJoinAcceptPayload<'a> {
    bytes: &'a [u8],
}

impl<'a> EncryptedJoinAcceptPayload<'a> {
    /// Parses and structurally validates an encrypted JoinAccept.
    #[inline]
    pub fn parse(bytes: &'a [u8]) -> Result<Self, Error> {
        validate_join_accept_structure(bytes)?;
        Ok(Self { bytes })
    }

    /// The raw frame bytes.
    #[inline]
    pub fn as_bytes(&self) -> &'a [u8] {
        self.bytes
    }
}

/// A decrypted JoinAccept, borrowing the buffer that was decrypted in place.
#[derive(Debug)]
pub struct DecryptedJoinAcceptPayload<'a> {
    bytes: &'a [u8],
}

/// The optional channel frequency list of a JoinAccept, fully owned.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CfList {
    /// CFList type 0: five additional channel frequencies.
    DynamicChannel([Frequency; 5]),
    /// CFList type 1: a 72-entry channel mask for fixed-plan regions.
    FixedChannel(ChannelMask<9>),
}

impl<'a> DecryptedJoinAcceptPayload<'a> {
    /// Parses `buf` and decrypts it in place.
    ///
    /// Does NOT verify the MIC (it only becomes readable after decryption);
    /// prefer [`Self::check_mic_and_decrypt_in_place`].
    #[inline]
    pub fn decrypt_in_place<C: Crypto>(buf: &'a mut [u8], crypto: &C) -> Result<Self, Error> {
        validate_join_accept_structure(buf)?;
        // The device side runs AES *encryption* to invert the server's
        // decrypt-mode transformation, per the spec.
        for block in buf[1..].chunks_exact_mut(16) {
            crypto.encrypt_block(block);
        }
        Ok(Self { bytes: buf })
    }

    /// Decrypts in place, then verifies the MIC.
    ///
    /// Because the MIC only becomes readable after decryption, `buf` has
    /// already been transformed when `InvalidMic` is returned; with the wrong
    /// key that leaves it garbage, not the received bytes. Unlike the data
    /// frame path, a failed authentication here cannot leave the buffer
    /// untouched. Callers that want to retry with another key or log the
    /// original frame must keep a copy.
    #[inline]
    pub fn check_mic_and_decrypt_in_place<C: Crypto>(
        buf: &'a mut [u8],
        crypto: &C,
    ) -> Result<Self, Error> {
        let decrypted = Self::decrypt_in_place(buf, crypto)?;
        if !decrypted.validate_mic(crypto) {
            return Err(Error::InvalidMic);
        }
        Ok(decrypted)
    }

    /// Whether the MIC matches under the device's root key.
    ///
    /// `crypto` must be bound to the AppKey.
    #[inline]
    pub fn validate_mic<C: Crypto>(&self, crypto: &C) -> bool {
        let without_mic = &self.bytes[..self.bytes.len() - MIC_LEN];
        self.mic() == securityhelpers::calculate_mic(without_mic, crypto)
    }

    /// The server nonce (called AppNonce before LoRaWAN 1.0.4).
    #[inline]
    pub fn join_nonce(&self) -> JoinNonce {
        JoinNonce::from_wire_bytes(arr(&self.bytes[1..4]))
    }

    #[inline]
    pub fn net_id(&self) -> NetId {
        NetId::from_wire_bytes(arr(&self.bytes[4..7]))
    }

    #[inline]
    pub fn dev_addr(&self) -> DevAddr {
        DevAddr::from_wire_bytes(arr(&self.bytes[7..11]))
    }

    #[inline]
    pub fn dl_settings(&self) -> DLSettings {
        DLSettings::new(self.bytes[11])
    }

    /// The RX1 delay in seconds (1..=15; the wire value 0 means 1).
    #[inline]
    pub fn rx_delay(&self) -> u8 {
        self.bytes[12] & 0x0f
    }

    /// The channel frequency list, when present and of a known type.
    ///
    /// Returns `None` both when the frame carries no CFList and when the
    /// CFList type octet is RFU, as the retired parser did.
    #[inline]
    pub fn c_f_list(&self) -> Option<CfList> {
        if self.bytes.len() == JOIN_ACCEPT_LEN {
            return None;
        }
        let cflist = &self.bytes[13..29];
        match cflist[15] {
            0 => {
                let mut freqs = [Frequency::default(); 5];
                for (freq, chunk) in freqs.iter_mut().zip(cflist.chunks_exact(3)) {
                    *freq = Frequency::from_wire_bytes(arr(chunk));
                }
                Some(CfList::DynamicChannel(freqs))
            }
            1 => Some(CfList::FixedChannel(ChannelMask::new_from_raw(&cflist[..9]))),
            _ => None,
        }
    }

    #[inline]
    pub fn mic(&self) -> MIC {
        extract_mic(self.bytes)
    }

    /// The raw (decrypted) frame bytes.
    #[inline]
    pub fn as_bytes(&self) -> &'a [u8] {
        self.bytes
    }

    /// Derives the network session key for this join.
    ///
    /// `crypto` must be bound to the AppKey.
    #[inline]
    pub fn derive_nwkskey<C: Crypto>(&self, dev_nonce: DevNonce, crypto: &C) -> NwkSKey {
        NwkSKey(self.derive_session_key(0x01, dev_nonce, crypto))
    }

    /// Derives the application session key for this join.
    ///
    /// `crypto` must be bound to the AppKey.
    #[inline]
    pub fn derive_appskey<C: Crypto>(&self, dev_nonce: DevNonce, crypto: &C) -> AppSKey {
        AppSKey(self.derive_session_key(0x02, dev_nonce, crypto))
    }

    fn derive_session_key<C: Crypto>(
        &self,
        first_byte: u8,
        dev_nonce: DevNonce,
        crypto: &C,
    ) -> AES128 {
        let mut block = [0u8; 16];
        block[0] = first_byte;
        block[1..4].copy_from_slice(self.join_nonce().as_wire_bytes());
        block[4..7].copy_from_slice(self.net_id().as_wire_bytes());
        block[7..9].copy_from_slice(dev_nonce.as_wire_bytes());
        crypto.encrypt_block(&mut block);
        AES128(block)
    }
}

// --- Fixed-size wire fields ----------------------------------------------
//
// Every multi-byte LoRaWAN field is transmitted least-significant-byte
// first. Each type here stores the bytes in wire order and offers explicit
// conversions to and from the logical integer value, so byte order is
// decided at exactly one place instead of at every call site.

/// Error from parsing a fixed-size hex string.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ParseHexError;

impl core::fmt::Display for ParseHexError {
    #[inline]
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("expected a fixed-size hex string")
    }
}

impl core::error::Error for ParseHexError {}

/// Copies a slice into a fixed array. Callers guarantee `slice.len() == N`
/// through parse-time validation (see `Layout` in the data module and the
/// length checks in the join module).
#[inline]
pub(crate) fn arr<const N: usize>(slice: &[u8]) -> [u8; N] {
    let mut out = [0u8; N];
    out.copy_from_slice(slice);
    out
}

macro_rules! wire_value_newtype {
    (
        $(#[$outer:meta])*
        $name:ident([u8; $n:literal], $int:ty)
    ) => {
        $(#[$outer])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
        #[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
        #[cfg_attr(feature = "defmt-03", derive(defmt::Format))]
        pub struct $name([u8; $n]);

        impl $name {
            pub const BYTE_LEN: usize = $n;

            /// Constructs from bytes in wire (transmission) order, LSB first.
            #[inline]
            pub const fn from_wire_bytes(bytes: [u8; $n]) -> Self {
                Self(bytes)
            }

            /// Constructs from the logical value.
            #[inline]
            pub fn from_value(value: $int) -> Self {
                let le = value.to_le_bytes();
                let mut bytes = [0u8; $n];
                bytes.copy_from_slice(&le[..$n]);
                Self(bytes)
            }

            /// The bytes in wire (transmission) order, LSB first.
            #[inline]
            pub const fn as_wire_bytes(&self) -> &[u8; $n] {
                &self.0
            }

            /// The logical value.
            #[inline]
            pub fn value(&self) -> $int {
                let mut le = [0u8; core::mem::size_of::<$int>()];
                le[..$n].copy_from_slice(&self.0);
                <$int>::from_le_bytes(le)
            }
        }

        impl From<$int> for $name {
            #[inline]
            fn from(value: $int) -> Self {
                Self::from_value(value)
            }
        }

        impl From<$name> for $int {
            #[inline]
            fn from(v: $name) -> Self {
                v.value()
            }
        }

        /// Hex-formats the logical value MSB first, the conventional display
        /// order.
        impl core::fmt::Display for $name {
            #[inline]
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                write!(f, "{:0width$x}", self.value(), width = 2 * $n)
            }
        }

        /// Parses the conventional MSB-first hex form.
        impl core::str::FromStr for $name {
            type Err = ParseHexError;

            #[inline]
            fn from_str(s: &str) -> Result<Self, Self::Err> {
                if s.len() != 2 * $n {
                    return Err(ParseHexError);
                }
                let value = <$int>::from_str_radix(s, 16).map_err(|_| ParseHexError)?;
                Ok(Self::from_value(value))
            }
        }
    };
}

wire_value_newtype! {
    /// A 32-bit LoRaWAN device address.
    ///
    /// `DevAddr::from_value(0x01020304).as_wire_bytes()` is
    /// `[0x04, 0x03, 0x02, 0x01]`.
    DevAddr([u8; 4], u32)
}

impl DevAddr {
    /// The 7-bit network identifier (NwkID) in the most significant bits.
    #[inline]
    pub const fn nwk_id(&self) -> u8 {
        self.0[3] >> 1
    }
}

wire_value_newtype! {
    /// The 64-bit extended unique identifier of an end-device.
    ///
    /// Matches the conventions of [`crate::keys::DevEui`]: wire bytes are
    /// LSB first, `Display`/`FromStr` use the MSB-first form printed on
    /// device labels.
    DevEui([u8; 8], u64)
}

wire_value_newtype! {
    /// The 64-bit identifier of the join server (AppEUI before LoRaWAN
    /// 1.0.4).
    JoinEui([u8; 8], u64)
}

impl From<crate::keys::DevEui> for DevEui {
    #[inline]
    fn from(eui: crate::keys::DevEui) -> Self {
        Self::from_wire_bytes(arr(eui.as_ref()))
    }
}

impl From<DevEui> for crate::keys::DevEui {
    #[inline]
    fn from(eui: DevEui) -> Self {
        Self::from(*eui.as_wire_bytes())
    }
}

impl From<crate::keys::AppEui> for JoinEui {
    #[inline]
    fn from(eui: crate::keys::AppEui) -> Self {
        Self::from_wire_bytes(arr(eui.as_ref()))
    }
}

impl From<JoinEui> for crate::keys::AppEui {
    #[inline]
    fn from(eui: JoinEui) -> Self {
        Self::from(*eui.as_wire_bytes())
    }
}

wire_value_newtype! {
    /// The 32-bit multicast group address of a Remote Multicast Setup
    /// (TS005) session. Same wire shape as [`DevAddr`], kept distinct so the
    /// two cannot be interchanged.
    McAddr([u8; 4], u32)
}

wire_value_newtype! {
    /// The 16-bit device nonce from a JoinRequest.
    DevNonce([u8; 2], u16)
}

wire_value_newtype! {
    /// The 24-bit server nonce from a JoinAccept.
    ///
    /// Named AppNonce before LoRaWAN 1.0.4.
    JoinNonce([u8; 3], u32)
}

wire_value_newtype! {
    /// The 24-bit network identifier from a JoinAccept.
    NetId([u8; 3], u32)
}

/// A channel frequency, stored as the raw 24-bit wire value (units of 100 Hz).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "defmt-03", derive(defmt::Format))]
pub struct Frequency([u8; 3]);

impl Frequency {
    /// Constructs from bytes in wire (transmission) order, LSB first.
    #[inline]
    pub const fn from_wire_bytes(bytes: [u8; 3]) -> Self {
        Self(bytes)
    }

    /// Constructs from a frequency in Hz. Sub-100 Hz precision is lost.
    #[inline]
    pub fn from_hz(hz: u32) -> Self {
        let raw = hz / 100;
        let le = raw.to_le_bytes();
        Self([le[0], le[1], le[2]])
    }

    /// The frequency in Hz.
    #[inline]
    pub fn hz(&self) -> u32 {
        u32::from_le_bytes([self.0[0], self.0[1], self.0[2], 0]) * 100
    }

    /// The bytes in wire (transmission) order, LSB first.
    #[inline]
    pub const fn as_wire_bytes(&self) -> &[u8; 3] {
        &self.0
    }
}

/// The FCtrl octet, interpreted for the frame direction it came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt-03", derive(defmt::Format))]
pub struct FCtrl {
    byte: u8,
    uplink: bool,
}

impl FCtrl {
    #[inline]
    pub const fn new(byte: u8, uplink: bool) -> Self {
        Self { byte, uplink }
    }

    #[inline]
    pub const fn adr(&self) -> bool {
        self.byte & 0x80 != 0
    }

    /// ADR ACK requested; uplink only.
    #[inline]
    pub const fn adr_ack_req(&self) -> bool {
        self.uplink && self.byte & 0x40 != 0
    }

    #[inline]
    pub const fn ack(&self) -> bool {
        self.byte & 0x20 != 0
    }

    /// More downlink pending; downlink only.
    #[inline]
    pub const fn f_pending(&self) -> bool {
        !self.uplink && self.byte & 0x10 != 0
    }

    #[inline]
    pub const fn f_opts_len(&self) -> usize {
        (self.byte & 0x0f) as usize
    }

    #[inline]
    pub const fn raw_value(&self) -> u8 {
        self.byte
    }
}
