use std::env;
use std::fs::File;
use std::io::Write;
use std::path::Path;

fn main() {
    // Read location from environment variables, with defaults
    let lat = env::var("GNSS_LAT")
        .ok()
        .and_then(|s| s.parse::<f32>().ok())
        .unwrap_or(19.6925);

    let lon = env::var("GNSS_LON")
        .ok()
        .and_then(|s| s.parse::<f32>().ok())
        .unwrap_or(-98.8438);

    // Generate the constants file
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("gnss_location.rs");
    let mut f = File::create(&dest_path).unwrap();

    writeln!(f, "// Auto-generated by build.rs").unwrap();
    writeln!(f, "// Set GNSS_LAT and GNSS_LON environment variables to override").unwrap();
    writeln!(f, "pub const GNSS_LATITUDE: f32 = {:.6};", lat).unwrap();
    writeln!(f, "pub const GNSS_LONGITUDE: f32 = {:.6};", lon).unwrap();

    // Tell Cargo to rerun if env vars change
    println!("cargo:rerun-if-env-changed=GNSS_LAT");
    println!("cargo:rerun-if-env-changed=GNSS_LON");
}
